version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-calendar-app-back
    image: node:12
    working_dir: /usr/src/calendar-app-back
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/calendar-app-back
    volumes:
      - ./dist/:/usr/src/calendar-app-back/dist/
      - ./package.json:/usr/src/calendar-app-back/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo